### ISSUE TITLE
[Erro] - IndexError: list index out of range

### ISSUE THREAD

**Issue by sansaoipb** [gtkpad/downdetector_scrapper#5]
Parece que algo mudou no site, pode indicar como corrigir?

Traceback (most recent call last):
  File "C:/Users/eracydes.junior/PycharmProjects/StateGrid/Projetos/Python3/Downdetector/downdetector.py", line 97, in <module>
    status = dataParse.attrs["class"][2].split('-')[1]
IndexError: list index out of range

**Comment by swenilton** [comment]
Fiz uma "adaptação técnica" rsrs no arquivo [`downdetector.py`](https://pastebin.com/2fXcvaaR) enquanto sai uma correção.

**Comment by sansaoipb** [comment]
@swenilton peguei para testar este projeto hoje, e não sabia quais eram os parâmetros de consulta, 
Estava mexendo aqui, e cheguei nas mesmas strings e tbm tratei com base nelas... rs

![image](https://user-images.githubusercontent.com/17461376/110542330-ae107380-8107-11eb-8385-c294eaee103b.png)

**Comment by gtkpad** [comment]
Bom dia, Corrigi a implementação do parse_result, houve uma alteração na estrutura html do site.
